### ISSUE TITLE
Adding new Rows

### ISSUE THREAD

**Issue by artjomg** [awsp/handsontable-meteor#28] opened 2016-03-03 20:30 UTC
Hi, is there any example how to create new Collection items each time a new row is added?
Would be great.

Thanks.

**Comment by awsp** [comment] 2016-03-03 23:59
You will need to do it on the client side, see [this](https://docs.handsontable.com/0.23.0/Hooks.html#event:afterChange)

```
var hot = new Handsontable(document.getElementById('example'), {
  afterChanges: function (changes, source) {
    // changes is a size of 4 array, row, col, fromValue, toValue
    // Fire off a Meteor method to insert/update
  }
})
```

To receive data modified from another client, you will need to do something like this, (that assume you have already done the pub/sub. )

```
var cursor = Todo.find();
cursor.observeChanges({
  added: function (id, fields) {
    // Update your hot instance, the easiest way is to do hot.loadData() again
    // Or you could do the alter() method, but you will have to manage the position of all data. 
  }
});
```

Hope it helps

**Comment by artjomg** [comment] 2016-03-04 08:43
Hi and Thanks for your response,
currently I am not using your smart package, but directly the package by including the .min.js and the min.css files. I also figured out yesterday how the things are working.
Especially important for me is the paste event. But the issue I am facing currently is that using the SimpleSchema+vermongo the validation fails on null values when I copy and paste a row, so I have to clean up this array somehow or use a utility method which I simply don't know.

```
    Template.handsonTable.rendered = function () {
      var myData = [];  // Need this to create instance
      var container = document.getElementById("articles_handsonTable");
      var hot = new Handsontable(container,{  // Create Handsontable instance
        data: myData,
        startRows: 5,
        startCols: 5,
        colHeaders: true,
        minSpareRows: 1,
        contextMenu: true,
        afterChange: function (change, source) {  // "change" is an array of arrays.
        if (source == "paste"){
          for (i = 0; i < change.length; i++) {   // For each change, get the change info and update the record
              var rowNum = change[i][0]; // Which row it appears on Handsontable
              var row = myData[rowNum];  // Now we have the whole row of data, including _id
              /*var key = change[i][1];  // Handsontable docs calls this "prop"
              var oldVal = change[i][2];
              var newVal = change[i][3];*/
              //var setModifier = {$set: row};   // Need to build $set object
              //setModifier.$set[key] = newVal; // So that we can assign 'key' dynamically using bracket notation of JavaScript object
              //Articles.insert(null,setModifier);
              Articles.insert(row);
          }
        }else if (source !== "loadData") {  // Don't need to run this when data is loaded
            for (i = 0; i < change.length; i++) {   // For each change, get the change info and update the record
                var rowNum = change[i][0]; // Which row it appears on Handsontable
                var row = myData[rowNum];  // Now we have the whole row of data, including _id
                var key = change[i][1];  // Handsontable docs calls this "prop"
                var oldVal = change[i][2];
                var newVal = change[i][3];
                var setModifier = {$set: {}};   // Need to build $set object
                setModifier.$set[key] = newVal; // So that we can assign 'key' dynamically using bracket notation of JavaScript object
                Articles.update(row._id,setModifier);
            }
          }
        }
      });
```

Articles.insert(row); fails at the moment.

**Comment by joaopiopedreira** [comment] 2016-03-04 22:42
Hi, you can change the null fields in the table array prior to insertion. Check which fields are null and 1) set default values in simple schema or 2) set their values in the afterChange hook before insert them into the database.

João Pio Pedreira
/// Sent from a mobile device ///

**Comment by awsp** [comment] 2016-03-04 22:58
Side note: It's also recommended to do it on meteor server side instead of doing it straightly on client side as you would like to remove the insecure package. 

I am closing this issue as the issue is not related to the package . ;)

**Closed as completed** 2016-03-04 22:59 UTC
